.\" Copyright (c) 2026 Sergey A. Osokin
.\"
.\" This software was developed by Sergey A. Osokin <osa@FreeBSD.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd September 25, 2026
.Dt EPPCTL 8
.Os
.Sh NAME
.Nm eppctl
.Nd list and modify CPU Energy/Performance properties
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl s Ar value
.Sh DESCRIPTION
The
.Nm
utility is used to set and display CPU Energy/Performance properties.
.Pp
The options are as follows:
.Bl -tag -width "-s value"
.It Fl s Ar value
Choose a specific value from 0 to 100.
.It Fl h
Print a help message.
.El
.Sh SEE ALSO
.Xr hwpstate_intel 4 ,
.Xr sysctl 8
.Sh HISTORY
The
.Nm
utility is not a part of the
.Fx
distribution yet.
.Sh AUTHORS
The
.Nm
utility was implemented by
.An Sergey A. Osokin Aq Mt osa@FreeBSD.org
.Sh BUGS
It is impossible to update or change value for a specific CPU yet.
